ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR','BC_SENSOR', 'SEMANTIC_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 720
    HEIGHT: 720
  SEMANTIC_SENSOR:
    WIDTH: 720
    HEIGHT: 720
  DEPTH_SENSOR:
    WIDTH: 720
    HEIGHT: 720
  BC_SENSOR:
    HEIGHT: 720
    WIDTH: 720
    HFOV: 90
    POSITION: [0, 0.25, 0] #this is relative to the base of the agents
    TYPE: HabitatSimBCSensor


TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2
  SENSORS: ['POINTGOAL_SENSOR']
  POINTGOAL_SENSOR:
    TYPE: PointGoalSensor
    GOAL_FORMAT: POLAR

  MEASUREMENTS: ['SPL']
  GOAL_SENSOR_UUID: pointgoal
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2

